### PR TITLE
feat!: too many features that I can't describe

### PR DESCRIPTION
**Pull request by jamestansx**
Use kbhit instead of GetAsyncKeyState.

Btw, do you consider to remove the `press any key to start` prompt as it is not centered and it is kinda ugly?

### CODE REVIEW

**Comment by Steveo-O** [comment]
maybe i will change it to repeat printing to become nicer

**Comment by jamestansx** [comment]
Ready to merge!!

but.. the leaderboard cannot print more than 40 persons, should I just limit them to just 40 entries?

**Comment by jamestansx** [comment]
`+845 −439` OMG

**Comment by jamestansx** [comment]
LGTM!

**Comment by Steveo-O** [comment]
Jesus so many changes?

**Comment by Steveo-O** [comment]
> Ready to merge!!
> 
> but.. the leaderboard cannot print more than 40 persons, should I just limit them to just 40 entries?

Noo way need to have delete line as well?

**Comment by jamestansx** [comment]
> > Ready to merge!!
> > 
> > but.. the leaderboard cannot print more than 40 persons, should I just limit them to just 40 entries?
> 
> Noo way need to have delete line as well?

I solved it. I just displayed the first `SCREEN_HEIGHT` amount of entries.

**Pull request merged**
