### PR TITLE
feat: a bunch of new stuff

### PR DESCRIPTION
**Pull request by jamestansx**
Features:

- render all characters in 4 grid
- use nice ASCII code to render walls and dots

Fixes:
- the warning about type `auto` as parameter is fixed
- default maps will be loaded if no maps are found

P/S: If there's anything don't understand, call me!!!

### CODE REVIEW

**Comment by Steveo-O** [comment]
Wowowowow

**Comment by jamestansx** [comment]
Done, ready to merge!

**Comment by jamestansx** [comment]
TODO: change the default accordingly

**Comment by Steveo-O** [comment]
YEAHAW

**Pull request merged**
